"""Add more google places fields in Restaurant

Revision ID: 3c38a3142441
Revises: bf50ffbaa3d4
Create Date: 2025-11-04 05:05:31.497738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c38a3142441'
down_revision: Union[str, Sequence[str], None] = 'bf50ffbaa3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('current_opening_hours', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('secondary_opening_hours', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('international_phone_number', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('opening_hours', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('price_level', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'website')
    op.drop_column('restaurants', 'price_level')
    op.drop_column('restaurants', 'opening_hours')
    op.drop_column('restaurants', 'international_phone_number')
    op.drop_column('restaurants', 'secondary_opening_hours')
    op.drop_column('restaurants', 'current_opening_hours')
    # ### end Alembic commands ###
