"""Drop quotes column from listings

Revision ID: bf50ffbaa3d4
Revises: ef50f3809e6e
Create Date: 2025-10-31 16:22:21.926500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf50ffbaa3d4'
down_revision: Union[str, Sequence[str], None] = 'ef50f3809e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_listings_review_sections_gin'), table_name='listings', postgresql_using='gin')
    op.drop_column('listings', 'quotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('quotes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_listings_review_sections_gin'), 'listings', ['review_sections'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
