"""Add review_sections column to listings table

Revision ID: ef50f3809e6e
Revises: 9d5a40be699b
Create Date: 2025-10-31 11:19:24.029440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef50f3809e6e'
down_revision: Union[str, Sequence[str], None] = '9d5a40be699b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('review_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'review_sections')
    # ### end Alembic commands ###
